services:

  postgres-db:
    image: postgres:16
    container_name: tracker_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pricetracker
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: price_tracker_app
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db